### ISSUE TITLE
incorrect make install targets?

### ISSUE THREAD

**Issue by atelszewski** [KeithDHedger/ManPageEditor#2]
Hi,

When executing _make install_, it will perform the following actions at the end:

```
xdg-icon-resource install (...)
xdg-icon-resource install (...)
xdg-icon-resource install (...)
xdg-mime install ManPageEditor/resources/documenticons/maneditdoc-mime.xml
update-mime-database /usr/share/mime
gtk-update-icon-cache --force /usr/share/icons/hicolor
```

I really think those shouldn't be the part of _make install_, but rather are handled by package managers.

Could you remove this target or at least make it not run when invoking _make install_?
## Thanks!

Best regards,
Andrzej Telszewski

**Comment by KeithDHedger** [comment]
Hi

No this is correct, you would usually run make install as root, as certain files go into system folders, /usr/bin, those commands are needed to update the mime databases which need root permissions, I only supply source code I do not supply packages, ifnthere is a conflict then it is the package that is wrong not the makefiles, although I am willing to help out packagers as much as I can I can only support buliding/installing from source.

If you are packaging this and you are having problems it is up to you to patch the makefiles for your particular package manager, let me know if you need help with that.

Keith

Sent from Samsung tablet

-------- Original message --------

**Comment by atelszewski** [comment]
Hi,

I insist that it is not correct ;)

When executing _make install DESTDIR=/some/path_ you expect that the files are placed under /some/path and nothing outside is touched.

I understand that you want to make it easy to install from source, but you make life of packagers harder. My suggestion is that you separate the make targets, so that _make install_ installs the files under DESTDIR and does not do any outside changes and another target actually does that changes (e.g. the mime update, etc.). But this second target should not be executed by _make install_.

It is the role of packager to update the mime database, etc., _make install_ should just place the files in correct location. I'm coming from Slackware and in Slackware there is file that gets executed upon package installation and this file deals with all the necessary post-installation actions. Have a look [here](https://slackbuilds.org/slackbuilds/14.1/development/qt-creator3/doinst.sh) for an example.

If you want to leave it as is now, then please add comment in the README that _make install_ behaves in that way, since it is non standard.

Thanks for your help!

## 

Best regards,
Andrzej Telszewski

**Comment by KeithDHedger** [comment]
I will get back to you about this, I hadn't noticed that using destdir was putting files outside of sting error, busy today, but I will look at it asap

Keith

P.S.
I'm an ex slacker so am familier with slack packages.

Sent from Samsung tablet

-------- Original message --------

**Comment by KeithDHedger** [comment]
Hi Andrzej

I have ( hopefully! ) fixed the makefiles, and added a 
install-mimetypes/uninstall-mimetypes target, to the opt makefile, there 
are also instructions printed at the end of configure/make for 
installing from source and for packagers.
Git repo updated

Hope this helps.

Keith

**Comment by atelszewski** [comment]
Hi,

Seems to be fine now.

Thanks!

## 

Best regards,
Andrzej Telszewski

**Comment by KeithDHedger** [comment]
you're welcome, marked as closed
