### ISSUE TITLE
Release tags on github

### ISSUE THREAD

**Issue by atelszewski** [KeithDHedger/ManPageEditor#3]
Hi,

Could you tag releases on github please?
As you probably remember, Slackware guys prefer to have version string without dashes -, so that format would be well appreciated:)
Trying to download from http://gtk-apps.org/content/show.php/Man+Page+Editor+?content=160219 takes ages or I'm doing something terribly wrong.

Thanks in advance!
## 

Best regards,
Andrzej Telszewski

**Comment by KeithDHedger** [comment]
Use the download link directly:

https://dl.dropboxusercontent.com/s/urwrobf8gg4wpbr/ManPageEditor-0.1.0.tar.gz

The releases on git hub are a convienience, the wayvgithub names tge releases is awkward just download and rename.

Keith

Sent from Samsung tablet

-------- Original message --------

**Comment by KeithDHedger** [comment]
As an after thought there _are_ no releases on this repo, so closing this.

**Comment by KeithDHedger** [comment]
New release here:
https://dl.dropboxusercontent.com/s/vk99qwpz1iej4ht/ManPageEditor-0.1.1.tar.gz
