### ISSUE TITLE
can't change property 'name'

### ISSUE THREAD

**Issue by dodona2** [KeithDHedger/ManPageEditor#5]
If I change file/properties/name, and reload the file/properties dialog, the change of the value of the 'name' property is untouched.

**Comment by KeithDHedger** [comment]
Hi

Havn't noticed this before, not at my machine at the  moment, I will get back to you asap, if possible can you send me the file you are having troubles with, also are you building gt2 or gtk3 version, and what host os are you building on

thanks


Keith

Sent from Samsung tablet

-------- Original message --------

**Comment by KeithDHedger** [comment]
Can't duplicate this, changing the name in the properties dialog is fixed when you click OK, if you click CANCEL then the new name is discarded as it should be, can you supply more details, what version you are using gtk2/3, what host you are on etc and the file you are using, do you have permissions to write to the file you are opening?

**Comment by KeithDHedger** [comment]
unless i hear otherwise within the next 24 hours i will close this as solved

**Comment by KeithDHedger** [comment]
Closed as un-reproducable
