### ISSUE TITLE
can't change any properties

### ISSUE THREAD

**Issue by dodona2** [KeithDHedger/ManPageEditor#6]
try out that mpz. Its very simple on the scratch. I replace 'myprogram' by 'type' in file:propertiess:name an press the OK button, 'type' is replaced by 'myprogram' the next time I run file:propertiess:name. 

[Uploading type.mpz.zip…]()

**Comment by KeithDHedger** [comment]
Not at my machine at the moment I will look at it tomorrow

**Comment by KeithDHedger** [comment]
This link is broken, please send me the file directly, not via github, also please include the info i asked for before, this looks like a problem at your end probably permissions, try using save as to save the file to somewhere you have read write access to and then edit that file.

**Comment by dodona2** [comment]
posted it to your mailbox.

**Comment by KeithDHedger** [comment]
Closed as unreproducible.
